---
title: "County Factors Regression"
output: html_document
---

```{r setup, include=FALSE}
library(readr)
library(car)
library(tidyverse)
library(DataExplorer)
library(corrplot)
library(mice)
```

```{r}
indicators <- read_csv("~/ari_social_media/data/working/County_Level/county_level_indicators.csv") %>%
  dplyr::select(-c(pct_renter_occupied_homes, pct_moved_after_2014,  pct_moved_2010_2014, pct_moved_2000_2009, pct_moved_1990_1999, pct_moved_1980_1989, pct_moved_1979_earlier, pct_movers_within_county, pct_health_ins))

```

```{r}
plot_missing(indicators)

missing_indicators <- indicators %>%
  dplyr::select(-c(county, pct_lib_program_atten, lib_visit_rate, pct_lib_patrons, lib_hours_per_person, water_violations))%>%
  mutate(missing_hispanic_income = ifelse(is.na(median_income_hispanic), 1, 0),
         missing_income_black = ifelse(is.na(median_income_black), 1, 0),
         missing_bw_segregation = ifelse(is.na(segregation_black_white), 1, 0),
         missing_pcp = ifelse(is.na(pcp_ratio), 1, 0),
         missing_nw_segregation = ifelse(is.na(segregation_white_non), 1, 0),
         missing_death_rate = ifelse(is.na(death_rate), 1, 0),
         missing_prev_hosp = ifelse(is.na(preventable_hosp_rate), 1, 0))

missing_corr_plot <- round(cor(missing_indicators, use = "pair"), 2)

corrplot(missing_corr_plot,
         tl.col="black", tl.cex = 0.7, tl.srt = 45)
```

```{r}
#remove all variables with more than 20% missing, as well as water violations (appears to be missing not at random), and percent registered voted and percent less than high school (perfectly correlated with other variables)
indicators_2 <- indicators %>%
  dplyr::select(-c(pct_lib_program_atten, lib_visit_rate, pct_lib_patrons, lib_hours_per_person, water_violations, pct_reg_voted, pct_less_than_hs))

#impute missing variables
imputed <- mice(indicators_2, method = "pmm")
complete_indicators <- complete(imputed)
write_csv(complete_indicators, "~/ari_social_media/data/working/County_Level/county_level_indicators_w_imputation.csv")
#take out county name
complete_indicators_2 <- complete_indicators %>%
  dplyr::select(-c(county))
```



```{r}
# #remove all variables that contribute to multicolinearity
# indicators_dropped_cols <- indicators_2 %>%
#   dplyr::select(-c(pct_black, pct_native, pct_asian, pct_pacific_islander, pct_race_other, pct_private_health_ins, pct_public_health_ins, pct_some_college, pct_associates, pct_bachelors, pct_grad_degree, pct_hs_or_higher, pct_less_than_hs, pct_attained_hs, pct_fair_poor_health, pct_children_poverty, pct_food_insecure, median_income_white, median_income_black, median_income_hispanic, pct_child_food_insecure, pct_commute_drive, pct_commute_carpool, pct_commute_public, pct_commute_walk, pct_commute_other, pct_work_home, severe_housing_problems))
# 
# mod <- lm(pct_stayed~., data = indicators_dropped_cols)
# 
# car::vif(mod)
```

```{r}
library(car)
#remove variables that contribute to multicollinearity
complete_indicators_small <- complete_indicators_2 %>%
  dplyr::select(-c(pct_black, pct_native, pct_asian, pct_pacific_islander, pct_race_other, pct_commute_carpool, pct_commute_public, pct_commute_walk, pct_commute_other, pct_work_home, pct_private_health_ins, pct_public_health_ins, pct_attained_hs, pct_some_college, pct_associates, pct_bachelors, pct_grad_degree, pct_hs_or_higher, pct_college_or_higher, median_income_white, median_income_black, median_income_hispanic, pct_child_food_insecure, segregation_black_white, pct_registered, pct_children_poverty, pct_impoverished, pct_food_insecure, pct_fair_poor_health))

mod <- lm(pct_stayed~., data = complete_indicators_small)

car::vif(mod)
```

```{r}
library(glmnet)
# Find the best lambda using cross-validation
set.seed(123) 

cv.lasso <- cv.glmnet(model.matrix(pct_stayed~., complete_indicators_small)[,-1], complete_indicators_small$pct_stayed, alpha = 1, family = "gaussian")
# Fit the final model on the training data
model <- glmnet(model.matrix(pct_stayed~., complete_indicators_small)[,-1], complete_indicators_small$pct_stayed, alpha = 1, family = "gaussian",
                lambda = cv.lasso$lambda.min)
# Display regression coefficients
coef(model)
coef(cv.lasso, cv.lasso$lambda.1se)

selected_indicators_lasso <- complete_indicators_small %>%
  dplyr::select(population, pct_commute_drive, median_income, pct_owner_occupied_homes, pct_enrolled_prek, social_assoc_rate, segregation_white_non, segregation_white_non, pct_rural, pct_stayed)

mod <- lm(pct_stayed~., data = selected_indicators_lasso)
summary(mod)
```


```{r}
library(leaps)

models <- regsubsets(pct_stayed ~., data = complete_indicators_small, nvmax = 10, nbest=1)

summary(models)

selected_indicators_best <- complete_indicators_small %>%
  dplyr::select(population, pct_white, pct_commute_drive, commute_time_mean, median_income, pct_owner_occupied_homes, preventable_hosp_rate, air_pollution, segregation_white_non, pct_rural, pct_stayed)

mod2 <- lm(pct_stayed~., data = selected_indicators_best)
summary(mod2)
```

```{r}
model4 <- lm(pct_stayed~population+commute_time_mean+median_income+pct_owner_occupied_homes, data = complete_indicators_small)
summary(model4)

model5 <- lm(pct_stayed~population+pct_commute_drive+commute_time_mean+median_income+pct_owner_occupied_homes, data = complete_indicators_small)
summary(model5)

model6 <- lm(pct_stayed~population+pct_white+pct_commute_drive+commute_time_mean+median_income+pct_owner_occupied_homes, data = complete_indicators_small)
summary(model6)

model7 <- lm(pct_stayed~population+pct_commute_drive+median_income+pct_owner_occupied_homes+air_pollution+pct_rural+child_abuse_rate, data = complete_indicators_small)
summary(model7)

model8 <- lm(pct_stayed~population+pct_commute_drive+median_income+pct_owner_occupied_homes+air_pollution+segregation_white_non+pct_rural+child_abuse_rate, data = complete_indicators_small)
summary(model8)

model9 <- lm(pct_stayed~population+pct_commute_drive+median_income+pct_owner_occupied_homes+income_ratio+air_pollution+segregation_white_non+pct_rural+child_abuse_rate, data = complete_indicators_small)
summary(model9)

# model10 <- lm(pct_stayed~population+pct_white+pct_commute_drive+commute_time_mean+median_income+pct_owner_occupied_homes+preventable_hosp_rate+air_pollution+segregation_white_non+pct_rural, data = complete_indicators_small)
# summary(model10)

model10 <- lm(pct_stayed~population+pct_white+pct_commute_drive+commute_time_mean+median_income+income_ratio+air_pollution+segregation_white_non+pct_rural+pct_voted, data = complete_indicators_small)
summary(model10)
```

```{r}
summary(lm(pct_stayed~pct_commute_drive+commute_time_mean+median_income+income_ratio+air_pollution+pct_white+segregation_white_non+population+pct_rural+pct_voted, data = complete_indicators_small))

selected_10 <- complete_indicators_small %>%
  dplyr::select(population, pct_white, pct_commute_drive, commute_time_mean, median_income, income_ratio, air_pollution, segregation_white_non, pct_rural, pct_voted, pct_stayed)

selected_corr_plot <- round(cor(selected_10, use = "pair"), 2)

corrplot(selected_corr_plot,
         tl.col="black", tl.cex = 0.7, tl.srt = 45)
```

```{r}
selected_10_no_y <- selected_10 %>%
  dplyr::select(-c(pct_stayed))

pr.indicators <- prcomp(x = selected_10_no_y[,], scale=TRUE, center=TRUE)

biplot(pr.indicators, col = c("white", "black"))

```